version: '3.8'
services:
  backend:
    build: ./server
    ports:
      - "4500:4500"
    networks:
      - mern-network

  frontend:
    build: ./client
    ports:
      - "4000:4000"
    depends_on:
      - backend
    networks:
      - mern-network

networks:
  mern-network:
    driver: bridge
